include ~/.cache/wal/colors-kitty.conf
cursor_trail 1
window_padding_width 10 15
cursor_shape underline
cursor #5F676A
#cursor #8EBBCA
cursor_thickness 2.0
shell_integration no-cursor

tab_bar_style powerline 
tab_powerline_style slanted
tab_bar_align left
