#!/usr/bin/env python3
"""Generate Cava gradients from the palette used by Hyprland borders."""

import json
from pathlib import Path


PALETTE = Path.home() / ".cache" / "wal" / "colors.json"
THEME = Path.home() / ".config" / "cava" / "themes" / "wallpaper"
CONFIG = Path.home() / ".config" / "cava" / "config"
START_MARKER = "# BEGIN WALLPAPER GRADIENT"
END_MARKER = "# END WALLPAPER GRADIENT"


def rgb(color: str) -> tuple[int, int, int]:
    value = color.lstrip("#")
    return tuple(int(value[index:index + 2], 16) for index in (0, 2, 4))


def mix(left: str, right: str, amount: float) -> str:
    a, b = rgb(left), rgb(right)
    channels = (round(x + (y - x) * amount) for x, y in zip(a, b))
    return "#" + "".join(f"{channel:02x}" for channel in channels)


def main() -> None:
    palette = json.loads(PALETTE.read_text())
    colors = palette["colors"]

    # These are the same two endpoints used by col.active_border.
    primary = colors["color4"]
    accent = colors["color6"]
    glow = colors["color7"]

    # The vertical gradient follows bar height, while the horizontal gradient
    # paints the border colors across the spectrum on supported Cava outputs.
    vertical = [
        primary,
        mix(primary, accent, 0.20),
        mix(primary, accent, 0.40),
        mix(primary, accent, 0.60),
        mix(primary, accent, 0.80),
        accent,
        mix(accent, glow, 0.35),
        mix(accent, glow, 0.68),
    ]
    horizontal = [
        primary,
        mix(primary, accent, 0.30),
        mix(primary, accent, 0.62),
        accent,
        mix(primary, accent, 0.62),
        mix(primary, accent, 0.30),
        primary,
    ]

    settings = [
        "# Generated by ~/.config/hypr/scripts/cava-wallpaper-theme.py",
        "# Uses the same color4 -> color6 palette as the Hyprland active border.",
        "gradient = 1",
        *(f"gradient_color_{index} = '{color}'"
          for index, color in enumerate(vertical, 1)),
        "",
        "horizontal_gradient = 1",
        *(f"horizontal_gradient_color_{index} = '{color}'"
          for index, color in enumerate(horizontal, 1)),
        "blend_direction = 'up'",
        "",
    ]

    THEME.parent.mkdir(parents=True, exist_ok=True)
    temporary = THEME.with_suffix(".tmp")
    temporary.write_text("\n".join(settings))
    temporary.replace(THEME)

    # Keep the settings inline as well. Some launchers or old live Cava
    # processes do not consistently follow updates to an external theme file.
    config = CONFIG.read_text()
    start = config.index(START_MARKER) + len(START_MARKER)
    end = config.index(END_MARKER)
    inline = "\n" + "\n".join(settings) + "\n"
    temporary = CONFIG.with_suffix(".tmp")
    temporary.write_text(config[:start] + inline + config[end:])
    temporary.replace(CONFIG)


if __name__ == "__main__":
    main()
