#!/usr/bin/env python3
import json
import sys
from pathlib import Path


HOME = Path.home()
COLORS_JSON = HOME / ".cache" / "wal" / "colors.json"
CURRENT_WALLPAPER = HOME / ".cache" / "wallpaper-colors" / "current"
OUT = HOME / ".config" / "rofi" / "wallpaper-colors.rasi"

FALLBACK = {
    "special": {
        "background": "#121318",
        "foreground": "#e2e2e9",
    },
    "colors": {
        "color0": "#121318",
        "color1": "#b0c6ff",
        "color2": "#1e1f25",
        "color4": "#b0c6ff",
        "color6": "#c8d3ff",
        "color8": "#8f9099",
        "color9": "#d6e0ff",
    },
}


def color(data, section, key, default):
    value = data.get(section, {}).get(key, default)
    if isinstance(value, str) and value.startswith("#") and len(value) == 7:
        return value
    return default


def rgb(hex_color):
    value = hex_color.lstrip("#")
    return tuple(int(value[i:i + 2], 16) for i in (0, 2, 4))


def rgba(hex_color, alpha):
    r, g, b = rgb(hex_color)
    return f"rgba({r}, {g}, {b}, {alpha})"


def rasi_quote(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def current_wallpaper(argv):
    if len(argv) > 1 and Path(argv[1]).is_file():
        return Path(argv[1])
    if CURRENT_WALLPAPER.is_file():
        candidate = Path(CURRENT_WALLPAPER.read_text().strip()).expanduser()
        if candidate.is_file():
            return candidate
    return None


def main():
    data = FALLBACK
    if COLORS_JSON.is_file():
        try:
            data = json.loads(COLORS_JSON.read_text())
        except json.JSONDecodeError:
            data = FALLBACK

    background = color(data, "special", "background", FALLBACK["special"]["background"])
    foreground = color(data, "special", "foreground", FALLBACK["special"]["foreground"])
    background_alt = color(data, "colors", "color2", FALLBACK["colors"]["color2"])
    muted = color(data, "colors", "color8", FALLBACK["colors"]["color8"])
    accent = color(data, "colors", "color4", FALLBACK["colors"]["color4"])
    accent_light = color(data, "colors", "color9", accent)
    accent_alt = color(data, "colors", "color6", accent_light)
    urgent = color(data, "colors", "color1", accent)

    wallpaper = current_wallpaper(sys.argv)
    wallpaper_image = "none"
    if wallpaper:
        wallpaper_image = f"url({rasi_quote(str(wallpaper))}, height)"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "\n".join(
            [
                "/* Generated by ~/.config/hypr/scripts/rofi-wallpaper-theme.py */",
                "* {",
                f"    rofi-bg:              {background};",
                f"    rofi-bg-alt:          {background_alt};",
                f"    rofi-bg-glass:        {rgba(background, '0.76')};",
                f"    rofi-bg-alt-glass:    {rgba(background_alt, '0.66')};",
                f"    rofi-fg:              {foreground};",
                f"    rofi-muted:           {muted};",
                f"    rofi-accent:          {accent_light};",
                f"    rofi-accent-alt:      {accent_alt};",
                f"    rofi-selected-bg:     {rgba(accent, '0.24')};",
                f"    rofi-selected-strong: {rgba(accent, '0.38')};",
                f"    rofi-border:          {rgba(accent_alt, '0.55')};",
                f"    rofi-active:          {rgba(accent_alt, '0.30')};",
                f"    rofi-urgent:          {rgba(urgent, '0.35')};",
                f"    rofi-wallpaper-image: {wallpaper_image};",
                "",
                "    background:           @rofi-bg;",
                "    background-alt:       @rofi-bg-alt;",
                "    background-glass:     @rofi-bg-glass;",
                "    background-alt-glass: @rofi-bg-alt-glass;",
                "    foreground:           @rofi-fg;",
                "    selected-bg:          @rofi-selected-bg;",
                "    selected-fg:          @rofi-accent;",
                "    border-col:           @rofi-border;",
                "    selected:             @rofi-selected-strong;",
                "    active:               @rofi-active;",
                "    urgent:               @rofi-urgent;",
                "}",
                "",
            ]
        )
    )
    print(OUT)


if __name__ == "__main__":
    main()
