#!/usr/bin/env bash
set -euo pipefail

COLORS="$HOME/.cache/wal/colors.json"
OUTPUT="$HOME/.config/swaync/style.css"

[ -f "$COLORS" ] || exit 0
mkdir -p "$(dirname "$OUTPUT")"

python3 - "$COLORS" "$OUTPUT" <<'PY'
import json
import sys
from pathlib import Path

colors_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])


def clamp(value: int) -> int:
    return max(0, min(255, value))


def hex_to_rgb(value: str) -> tuple[int, int, int]:
    value = value.strip()
    if not value.startswith("#") or len(value) != 7:
        value = "#888888"
    return tuple(int(value[i:i + 2], 16) for i in (1, 3, 5))


def rgb_to_hex(rgb: tuple[int, int, int]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*(clamp(v) for v in rgb))


def mix(a: str, b: str, amount: float) -> str:
    ar, ag, ab = hex_to_rgb(a)
    br, bg, bb = hex_to_rgb(b)
    return rgb_to_hex((
        round(ar * (1 - amount) + br * amount),
        round(ag * (1 - amount) + bg * amount),
        round(ab * (1 - amount) + bb * amount),
    ))


def rgba(value: str, alpha: float) -> str:
    r, g, b = hex_to_rgb(value)
    return f"rgba({r}, {g}, {b}, {alpha:.2f})"


def is_gray(value: str) -> bool:
    red, green, blue = hex_to_rgb(value)
    return red == green == blue


data = json.loads(colors_path.read_text())
special = data.get("special", {})
palette = data.get("colors", {})

bg = special.get("background", palette.get("color0", "#111318"))
fg = special.get("foreground", palette.get("color15", "#e1e2e9"))
accent = palette.get("color6", palette.get("color9", "#a3c9ff"))
primary = palette.get("color4", accent)
secondary = palette.get("color10", mix(bg, fg, 0.74))
dim = palette.get("color8", mix(bg, fg, 0.56))

surface = mix(bg, fg, 0.055)
surface_hi = mix(bg, fg, 0.105)
button = mix(bg, fg, 0.16)
button_hi = mix(bg, accent, 0.20)
monochrome = all(is_gray(value) for value in (bg, fg, accent, primary))
critical = fg if monochrome else "#ffb4ab"
critical_bg = mix(bg, fg if monochrome else "#5d1218", 0.18 if monochrome else 0.48)
close_hover = rgba(critical, 0.42)

css = f"""/* Generated by ~/.config/hypr/scripts/swaync-colors.sh */
* {{
    font-family: "JetBrainsMono Nerd Font Propo";
    font-weight: bold;
    transition: all 0.2s ease;
}}

/* Control Center */
.control-center {{
    background: {rgba(bg, 0.90)};
    border-radius: 20px;
    border: 2px solid {rgba(accent, 0.78)};
    padding: 10px;
    margin: 8px;
    box-shadow: 0 4px 24px rgba(0, 0, 0, 0.62);
}}

.control-center-list {{
    background: transparent;
}}

.control-center-list-placeholder {{
    opacity: 0.45;
    color: {fg};
}}

/* Title Bar */
.widget-title {{
    background: {rgba(surface_hi, 0.72)};
    color: {fg};
    border-radius: 14px;
    padding: 8px 14px;
    margin-bottom: 6px;
    font-size: 13px;
}}

.widget-title > button {{
    background: {rgba(accent, 0.13)};
    color: {accent};
    border: none;
    border-radius: 10px;
    padding: 4px 10px;
    font-size: 12px;
}}

.widget-title > button:hover {{
    background: {rgba(accent, 0.24)};
}}

/* Do Not Disturb */
.widget-dnd {{
    background: {rgba(surface_hi, 0.72)};
    color: {fg};
    border-radius: 14px;
    padding: 8px 14px;
    margin-bottom: 6px;
    font-size: 12px;
}}

.widget-dnd > switch {{
    background: {rgba(button, 0.66)};
    border-radius: 20px;
    border: none;
}}

.widget-dnd > switch:checked {{
    background: {rgba(accent, 0.50)};
}}

.widget-dnd > switch slider {{
    background: {fg};
    border-radius: 20px;
    min-width: 18px;
    min-height: 18px;
}}

/* Label */
.widget-label {{
    color: {accent};
    font-size: 22px;
    padding: 4px 0;
}}

/* Buttons Grid */
.widget-buttons-grid {{
    background: {rgba(surface_hi, 0.72)};
    border-radius: 14px;
    padding: 8px;
    margin-bottom: 6px;
}}

.widget-buttons-grid > flowbox > flowboxchild > button {{
    background: {rgba(button, 0.58)};
    color: {secondary};
    border: none;
    border-radius: 12px;
    padding: 10px 16px;
    font-size: 16px;
    min-width: 48px;
    min-height: 36px;
}}

.widget-buttons-grid > flowbox > flowboxchild > button:hover {{
    background: {rgba(accent, 0.17)};
    color: {accent};
}}

/* MPRIS */
.widget-mpris {{
    background: {rgba(surface_hi, 0.72)};
    border-radius: 14px;
    padding: 10px;
    margin-bottom: 6px;
    color: {fg};
}}

.widget-mpris-player {{
    padding: 4px;
    border-radius: 12px;
}}

.widget-mpris-title {{
    font-weight: bold;
    font-size: 13px;
    color: {fg};
}}

.widget-mpris-subtitle {{
    font-size: 11px;
    color: {secondary};
}}

/* Notifications */
.notification-row {{
    outline: none;
    margin: 4px 0;
}}

.notification-row:focus,
.notification-row:hover {{
    opacity: 1;
}}

.notification {{
    background: {rgba(surface, 0.84)};
    border: 1px solid {rgba(dim, 0.36)};
    border-radius: 16px;
    padding: 0;
    margin: 0;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.52);
}}

.notification-content {{
    background: transparent;
    border-radius: 16px;
    padding: 12px;
}}

.notification-default-action {{
    background: transparent;
    border-radius: 16px;
    border: none;
    padding: 0;
    color: {fg};
}}

.notification-default-action:hover {{
    background: {rgba(accent, 0.09)};
}}

.notification-action {{
    background: {rgba(surface_hi, 0.78)};
    color: {accent};
    border: none;
    border-top: 1px solid {rgba(dim, 0.30)};
    border-radius: 0 0 14px 14px;
    padding: 6px;
    font-size: 11px;
}}

.notification-action:hover {{
    background: {rgba(accent, 0.14)};
}}

.close-button {{
    background: {rgba(button, 0.62)};
    color: {fg};
    border: none;
    border-radius: 20px;
    min-width: 22px;
    min-height: 22px;
    padding: 0;
    font-size: 11px;
}}

.close-button:hover {{
    background: {close_hover};
    color: {fg};
}}

.notification-label {{
    color: {fg};
    font-size: 13px;
    font-weight: bold;
}}

.notification-body {{
    color: {secondary};
    font-size: 12px;
    font-weight: normal;
}}

.notification-summary {{
    color: {fg};
    font-size: 13px;
    font-weight: bold;
}}

.notification-time {{
    color: {dim};
    font-size: 10px;
}}

/* Urgency tints */
.notification.low {{
    border-left: 3px solid {rgba(primary, 0.55)};
}}

.notification.normal {{
    border-left: 3px solid {rgba(accent, 0.82)};
}}

.notification.critical {{
    border-left: 3px solid {critical};
    background: {rgba(critical_bg, 0.87)};
}}

/* Popup notifications */
.floating-notifications {{
    background: transparent;
}}

.blank-window {{
    background: transparent;
}}
"""

output_path.write_text(css)
print(output_path)
PY

timeout 2 swaync-client -rs >/dev/null 2>&1 || true
