#
#   █████╗ ██████╗  ██████╗██╗  ██╗    ██╗     ██╗███╗   ██╗██╗   ██╗██╗  ██╗
#  ██╔══██╗██╔══██╗██╔════╝██║  ██║    ██║     ██║████╗  ██║██║   ██║╚██╗██╔╝
#  ███████║██████╔╝██║     ███████║    ██║     ██║██╔██╗ ██║██║   ██║ ╚███╔╝
#  ██╔══██║██╔══██╗██║     ██╔══██║    ██║     ██║██║╚██╗██║██║   ██║ ██╔██╗
#  ██║  ██║██║  ██║╚██████╗██║  ██║    ███████╗██║██║ ╚████║╚██████╔╝██╔╝ ██╗
#  ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝    ╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝
#
#  

source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/environment.conf
source = ~/.config/hypr/modules/looknfeel.conf
source = ~/.config/hypr/modules/bar-theme.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/windowrules.conf
