################
### ANIMATIONS ###
################

animations {
    enabled = yes

    bezier = fluent_decel, 0.05,0.9,0.1,1

    animation = workspaces, 1, 4, fluent_decel, slidevert
    animation = windows, 1, 2, fluent_decel, slide
}
