############################
### PROGRAMS & AUTOSTART ###
############################

$terminal = kitty
$fileManager = files
$menu = ~/.config/waybar/Scripts/launch.sh
$rofi = ~/rofi/files/launchers/type-6/launcher.sh
$qylock = /home/arch/.local/share/quickshell-lockscreen/lock.sh
$anicli = /home/arch/.local/bin/ani-cli --rofi

# exec-once = waybar
exec-once = fcitx5 &
exec-once = nm-applet &
exec-once = blueman-applet &
exec-once = awww-daemon
exec-once = wal -R
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = python3 /home/arch/startpage/z.startpage/scripts/media-bridge.py
exec-once = python3 /home/arch/startpage/z.startpage/scripts/stats-bridge.py
exec-once = quickshell -p ~/.config/quickshell/startpage/shell.qml
exec-once = ~/.config/waybar/Scripts/waybar-theme.sh --restore


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_IM_MODULE, fcitx
env = XMODIFIERS, @im=fcitx
env = SDL_IM_MODULE, fcitx
env = GLFW_IM_MODULE, ibus
# env = AQ_DRM_DEVICES,/dev/dri/by-path/pci-0000:00:02.0-card:/dev/dri/by-path/pci-0000:01:00.0-card
