##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/


# Ignore maximize requests
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix XWayland drag issues
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# hyprland-run popup
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# iwdgui floating window
windowrule {
    name = iwdgui-float
    match:class = .*[Ii]wdgui.*

    float = yes
    center = yes
    size = 720 520
}

# Pavucontrol floating window
windowrule {
    name = pavucontrol-float
    match:class = .*[Pp]avucontrol.*

    float = yes
    center = yes
    size = 900 600
}
