# Basic mpd.conf
music_directory    "~/Music"
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
log_file           "syslog"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"

audio_output {
    type            "pulse" # or "pipewire" if using pipewire-pulse
    name            "My Pulse Output"
}
